; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_cyber_menu=music_data_cyber_menu
.endif

music_data_cyber_menu:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : Cyber Menu
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_cyber_menu
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env4,@env5,@env2,@env8 ; 00 : Instrument 1
	.word @env3,@env5,@env7,@env1 ; 01 : Instrument 3
	.word @env0,@env9,@env6,@env1 ; 02 : Instrument 4

@env0:
	.byte $00,$c5,$02,$c4,$c3,$c2,$c1,$c1,$c0,$00,$08
@env1:
	.byte $00,$c0,$7f,$00,$02
@env2:
	.byte $c1,$c0,$00,$01
@env3:
	.byte $00,$c2,$c4,$c6,$c6,$c7,$c7,$c6,$02,$c5,$c4,$c3,$c2,$00,$0c
@env4:
	.byte $00,$c9,$ca,$ca,$cb,$cc,$cc,$cd,$04,$cc,$06,$cb,$02,$ca,$02,$c9,$02,$c8,$c8,$c7,$c7,$c6,$c6,$c5,$c5,$c4,$c4,$c3,$c2,$c1,$c0,$00,$1e
@env5:
	.byte $c0,$7f,$00,$01
@env6:
	.byte $7f,$00,$00
@env7:
	.byte $c2,$7f,$00,$00
@env8:
	.byte $00,$c2,$c2,$c1,$04,$c0,$00,$05
@env9:
	.byte $c0,$c0,$c1,$c0,$bf,$be,$bf,$c0,$c1,$c0,$00,$09

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $ff, $ff, $bf, $48, $ff, $8b, $80, $11, $cd, $00, $e1, $48
	.byte $b1, $11, $c3, $00, $ff, $9d, $14, $a5, $48, $a7, $00, $ff, $93, $18, $cf, $00, $99, $16, $91, $48, $bb, $00, $9b, $14
	.byte $cd, $00, $ff, $93, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
@song0ref49:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $ff, $ff, $bf, $ff, $8b, $82, $1d, $cd, $00, $e1, $b1, $1d, $c3, $00, $ff, $9d, $20, $a5, $a7, $00, $ff, $93, $24, $cf
	.byte $00, $99, $22, $91, $bb, $00, $9b, $20, $cd, $00, $ff, $93, $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $84
@song0ref109:
	.byte $20, $a5, $00, $87, $20, $87, $00, $87, $20, $87, $00, $87, $20, $87, $00, $89, $20, $a3, $00, $91, $20, $a3, $00, $93
	.byte $41, $18
	.word @song0ref109
	.byte $41, $15
	.word @song0ref109
	.byte $87, $9b, $00, $93
	.byte $41, $18
	.word @song0ref109
	.byte $41, $18
	.word @song0ref109
	.byte $41, $11
	.word @song0ref109
	.byte $8f, $93, $00, $91, $20, $a3, $00, $93
	.byte $41, $17
	.word @song0ref109
	.byte $89, $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $41, $0f
	.word @song0ref49
	.byte $42
	.word @song0ch4loop
