; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_cyber_theme=music_data_cyber_theme
.endif

music_data_cyber_theme:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : Cyber
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_cyber_theme
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env3,@env5,@env2,@env11 ; 00 : Instrument 1
	.word @env10,@env5,@env9,@env6 ; 01 : Instrument 2
	.word @env4,@env5,@env8,@env1 ; 02 : Instrument 3
	.word @env0,@env12,@env7,@env1 ; 03 : Instrument 4

@env0:
	.byte $00,$c5,$02,$c4,$c3,$c2,$c1,$c1,$c0,$00,$08
@env1:
	.byte $00,$c0,$7f,$00,$02
@env2:
	.byte $c1,$c0,$00,$01
@env3:
	.byte $00,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$00,$07
@env4:
	.byte $00,$c2,$c4,$c6,$c6,$c7,$c7,$c6,$02,$c5,$c4,$c3,$c2,$00,$0c
@env5:
	.byte $c0,$7f,$00,$01
@env6:
	.byte $00,$c0,$bf,$be,$bf,$c0,$04,$c1,$c2,$c3,$00,$09
@env7:
	.byte $7f,$00,$00
@env8:
	.byte $c2,$7f,$00,$00
@env9:
	.byte $c0,$c1,$00,$01
@env10:
	.byte $00,$c2,$03,$c3,$c4,$02,$c5,$00,$06
@env11:
	.byte $00,$c2,$c2,$c1,$04,$c0,$00,$05
@env12:
	.byte $c0,$c0,$c1,$c0,$bf,$be,$bf,$c0,$c1,$c0,$00,$09

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $80, $12, $87, $1c
@song0ref9:
	.byte $87, $16, $87, $12, $87
@song0ref14:
	.byte $18, $87, $16, $87, $1b, $87, $18, $87
@song0ref22:
	.byte $1e, $87, $1b, $87, $20, $87, $1e, $87, $12, $87, $20
	.byte $41, $18
	.word @song0ref9
	.byte $41, $0d
	.word @song0ref9
	.byte $48
	.byte $41, $0b
	.word @song0ref22
	.byte $41, $18
	.word @song0ref9
	.byte $41, $18
	.word @song0ref9
	.byte $87, $16, $87, $12, $87, $48
	.byte $41, $08
	.word @song0ref14
@song0ref58:
	.byte $1d, $87, $1b, $87, $20, $87, $1d, $87, $14, $87, $20
@song0ref69:
	.byte $87, $18, $87, $14, $87, $1a, $87, $18, $87, $1d, $87, $1a, $87, $20, $87, $1d, $87, $22, $87, $20, $87, $14, $87, $22
	.byte $41, $0d
	.word @song0ref69
@song0ref96:
	.byte $1f, $87, $1d, $87, $22, $87, $1f, $87, $48, $14, $87, $22
	.byte $41, $18
	.word @song0ref69
	.byte $41, $0d
	.word @song0ref69
	.byte $41, $08
	.word @song0ref96
	.byte $12, $87, $22
	.byte $41, $0d
	.word @song0ref9
	.byte $48
	.byte $41, $0b
	.word @song0ref22
	.byte $41, $0d
	.word @song0ref9
	.byte $41, $08
	.word @song0ref58
	.byte $10, $87, $20, $87, $14, $87, $10, $87
@song0ref141:
	.byte $16, $87, $14, $87, $19, $87, $16, $87, $1c, $87, $19, $87, $1e, $87, $1c, $87, $10, $87, $1e, $87, $14, $87, $10, $87
	.byte $48
	.byte $41, $08
	.word @song0ref141
	.byte $1b, $87, $19, $87, $1e, $87, $1b, $87, $0e, $87, $1e
@song0ref180:
	.byte $87, $12, $87, $0e, $87, $14, $87, $12, $87, $17, $87, $14, $87, $1a, $87, $17, $87, $1c, $87, $1a, $87, $0e, $87, $1c
	.byte $41, $0d
	.word @song0ref180
	.byte $19, $87, $17, $87, $1c, $87, $19, $87, $48, $00, $87, $1c
@song0ref219:
	.byte $87
@song0ref220:
	.byte $0e, $87, $00, $87, $12, $91, $14, $91, $17, $91, $19, $91, $1c, $91, $00, $87, $1a
	.byte $41, $0e
	.word @song0ref219
	.byte $a5, $00, $91, $48, $93
	.byte $41, $11
	.word @song0ref220
	.byte $41, $0e
	.word @song0ref219
	.byte $a5, $00, $91, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $00, $ff, $ff, $bd, $00, $ff, $ff, $bd, $82
@song0ref267:
	.byte $20, $cd, $22, $cd, $24, $f5, $22, $a5
	.byte $41, $08
	.word @song0ref267
	.byte $41, $08
	.word @song0ref267
	.byte $a7, $20, $cd, $1e, $ff, $9d, $1d, $a5, $a7, $00, $a5, $11, $cd, $00, $cd, $11, $cd, $00, $cd, $11, $cd, $00, $cd, $11
	.byte $cd, $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $00, $ff, $ff, $bd, $ff, $ff, $bf, $84
@song0ref318:
	.byte $2c, $cd, $2e, $cd, $30, $f5, $2e, $91, $00, $91
	.byte $41, $0a
	.word @song0ref318
	.byte $2a, $cd, $2c, $cd, $2e, $f5, $2c, $91, $00, $91, $2a, $cd, $29, $cd, $27, $f5, $25, $a5, $cf, $1d, $cd, $00, $cd, $1d
	.byte $cd, $00, $cd, $1d, $cd, $00, $cd, $1d, $cd, $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $86
@song0ref369:
	.byte $20, $a5, $20, $91, $20, $91, $20, $91, $20, $91, $20
@song0ref380:
	.byte $a5, $20, $a5, $20, $91, $20, $91, $20, $a5, $20, $91, $20, $8f, $20
	.byte $41, $19
	.word @song0ref369
	.byte $41, $19
	.word @song0ref369
	.byte $41, $19
	.word @song0ref369
	.byte $41, $19
	.word @song0ref369
	.byte $41, $19
	.word @song0ref369
@song0ref409:
	.byte $20, $a3, $20, $91, $20, $91, $20, $a7, $00
	.byte $41, $09
	.word @song0ref380
	.byte $00, $a5
	.byte $41, $09
	.word @song0ref409
	.byte $41, $09
	.word @song0ref380
	.byte $00, $a5, $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
@song0ref435:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf
	.byte $41, $09
	.word @song0ref435
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $42
	.word @song0ch4loop
